# -*- mode: Makefile -*-
%.obj: %.as
	$(AS) $(ASFLAGS) -C $<

%.as: %.c
	$(CC) $(CFLAGS) -S $<


%.d: %.c
	$(DEP) $(CPPFLAGS) -MM -MP $< -MF $@


.PHONY:  clean distclean deps


distclean: clean
	rm -f *.d
	sed '/\#\#\# Dependencies/q' < Makefile > make_tmp
	cp make_tmp Makefile
	rm make_tmp


%.d: %.as
	printf "$<: " > $@
	grep 'include' $< | awk '{print $$2}' | tr '\n' ' ' >> $@
	printf "\n" >> $@

%.lib:
	for i in $? ; do $(AR) r $@ $$i; done

dep:	$(DEPS)
	sed '/\#\#\# Dependencies/q' < Makefile > make_tmp
	cat $(DEPS) >> make_tmp
	cp make_tmp Makefile
	rm make_tmp
